apiVersion: v1
kind: Service
metadata:
  name: bulkintel-service
  namespace: bulkintel-dev
spec:
  selector:
    app: bulkintel
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
