apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: bulkintel-dev
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  loadBalancerIP: 10.0.0.191
  
